= Workon: Straight to the Point
Alexandre Beaulieu <alex@segfault.me>
v1.0 2018-11-27

Workon is a small script and accompanying plugins to make context switching
less painful. I wrote it because I was getting tired of always switching back
and forth between multiple projects and having to manually set up my workspace
every time.

It has not been tested much beyond my personal setup.

== Usage

`workon` is exposed as a function and must be sourced from your `.zshrc` or
`.bashrc` to work as intended.

`workon` uses the concept or workspaces to determine where to look for
projects. These workspaces are specified in a PATH-like syntax and can be
provided before sourcing the function. If not provided, the default is
`$HOME/Work`

A simple configuration looks like this: All projects in `Work` and `Dev` will
be considered by `workon`.

----
export WORKSPACES="$HOME/Work:$HOME/Dev"
source /path/to/workon
----

You can then use it by typing `workon <project>` on the command line.

== How it Works

Each directory in `$WORKSPACES` is iterated and a number of sequential checks
are performed. Very similarly to `PATH` resolution, the first workspace that
has a successful check will be used to start the new context. As soon as a
check passes, all subsequent workspaces and checks are ignored.

== Currently Supported (ordered by priority)

- `.tmuxinator.yml` in project directory
- tmuxinator `project.yml` in a workspace
- global tmuxinator project file in `~/.config/tmuxinator`
- Pipfile with `pipenv shell`
- Plain directory fallback (cd only)

== Future Work

The following is a list of things I would like to add at some point:

- Completion files for ZSH
- Additional Context Support (rvm, node, .env, ...)
- Support project templates and creation

